"""Multi-run stability: replay each scenario N times, report pass rate and timing spread.

    uv run python scripts/stability.py 20
"""

from __future__ import annotations

import json
import statistics
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
N = int(sys.argv[1]) if len(sys.argv) > 1 else 10
CASES = {
    "happy": ["-i", "member_id=10042"],
    "session-expiry": ["-i", "member_id=10042", "--inject", "expire_after=1"],
    "transient-503": ["-i", "member_id=10042", "--inject", "transient_503=1"],
    "tenant-overlay (pineridge)": ["-i", "member_id=10042", "-t", "pineridge"],
}

rows = []
with tempfile.TemporaryDirectory() as tmp:
    for name, extra in CASES.items():
        tenant = [] if "-t" in extra else ["-t", "harbor"]
        statuses, times, drift = [], [], 0
        for _ in range(N):
            p = subprocess.run(["uv", "run", "cua", "replay", "member.savings_balance.read", *tenant, *extra, "--evidence", tmp],
                               cwd=ROOT, capture_output=True, text=True)
            r = json.loads(p.stdout[p.stdout.index("{"):])
            statuses.append(r["status"])
            times.append(r["duration_ms"])
            drift += len(r["drift"])
        ok = statuses.count("success")
        rows.append(f"| {name} | {ok}/{N} | {statistics.median(times)} | {min(times)}–{max(times)} | {drift} |")
        print(rows[-1], flush=True)

out = ROOT / "evidence" / "STABILITY.md"
out.write_text(
    f"# Replay stability ({N} runs per case)\n\nGenerated by `uv run python scripts/stability.py {N}`.\n\n"
    "| case | success | median ms | range ms | drift signals |\n|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
)
print(f"wrote {out}")
